# Generated by Django 3.1.7 on 2021-05-11 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_local_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='回傳日期'),
        ),
    ]
