# Generated by Django 3.1.7 on 2021-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210511_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FJU1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FJU2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FJU3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
