# Generated by Django 3.1.7 on 2021-05-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210520_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='check',
            new_name='label',
        ),
    ]
