# Generated by Django 3.1.7 on 2021-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210520_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='Total',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='local',
            name='Aedes',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='local',
            name='Culex',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
