# Generated by Django 3.1.7 on 2021-05-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210520_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='CO2',
        ),
        migrations.RemoveField(
            model_name='local',
            name='PM',
        ),
    ]
