# Generated by Django 3.1.7 on 2021-05-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210520_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detection',
        ),
        migrations.DeleteModel(
            name='FJU1',
        ),
        migrations.DeleteModel(
            name='FJU2',
        ),
        migrations.DeleteModel(
            name='FJU3',
        ),
        migrations.RemoveField(
            model_name='local',
            name='CO2',
        ),
        migrations.RemoveField(
            model_name='local',
            name='PM',
        ),
    ]
