# Generated by Django 3.1.7 on 2021-05-24 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210520_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('year', models.CharField(default='', max_length=10)),
                ('month', models.CharField(default='', max_length=10)),
                ('day', models.CharField(default='', max_length=10)),
                ('temp', models.CharField(default='', max_length=10)),
                ('RH', models.CharField(default='', max_length=10)),
                ('Aedes', models.CharField(default='0', max_length=10)),
                ('Culex', models.CharField(default='0', max_length=10)),
                ('Total', models.CharField(default='0', max_length=10)),
                ('number', models.CharField(default='1', max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回傳日期')),
                ('label', models.CharField(default='', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
