# Generated by Django 3.1.7 on 2021-05-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_test_co2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
    ]
