# Generated by Django 3.1.7 on 2021-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='govern',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('Locations', models.CharField(default='', max_length=10)),
                ('City', models.CharField(default='', max_length=10)),
                ('Year', models.CharField(default='', max_length=10)),
                ('Month', models.CharField(default='', max_length=10)),
                ('Week', models.CharField(default='', max_length=10)),
                ('SO2', models.CharField(default='', max_length=10)),
                ('CO', models.CharField(default='', max_length=10)),
                ('O3', models.CharField(default='', max_length=10)),
                ('PM10', models.CharField(default='', max_length=10)),
                ('PM25', models.CharField(default='', max_length=10)),
                ('Nox', models.CharField(default='', max_length=10)),
                ('No', models.CharField(default='', max_length=10)),
                ('No2', models.CharField(default='', max_length=10)),
                ('TEMP', models.CharField(default='', max_length=10)),
                ('RH', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
