# Generated by Django 3.1.7 on 2021-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_govern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govern',
            name='CO',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='Locations',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='Month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='No',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='No2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='Nox',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='O3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='PM10',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='PM25',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='RH',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='SO2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='TEMP',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='Week',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='Year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='govern',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
