# Generated by Django 3.1.7 on 2021-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210604_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='govern',
            name='CC',
            field=models.CharField(default='', max_length=20),
        ),
    ]
