# Generated by Django 3.1.7 on 2021-06-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_govern_cc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='govern',
            old_name='Month',
            new_name='code',
        ),
    ]
