# Generated by Django 3.1.7 on 2021-06-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210604_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govern',
            name='code',
        ),
    ]
