# Generated by Django 3.1.7 on 2021-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_govern_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='govern',
            name='Month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
